### ISSUE TITLE
Current docker based build is broken

### ISSUE THREAD

**Issue by EugenMayer** [ianw1974/zimbra-build-scripts#58]
Building within the docker-image i get 

```bash
/home/git/zimbra/zm-mailbox/build.xml:13: The following error occurred while executing this line:
/home/git/zimbra/zm-mailbox/build-common.xml:576: Directory does not exist: /root/.ivy2/cache
```

Should be at least reproduceable when running a Zimbra 10.0.5 build

**Comment by ianw1974** [comment]
What OS are you attempting to build for?  Ubuntu 18.04 and 20.04 builds work.  Someone had this with Ubuntu 16.04 which I no longer support.  See: https://github.com/ianw1974/zimbra-build-scripts/issues/15 if it is related to Ubuntu 16.04.

It works for currently for Alma, CentOS, Oracle, Rocky, Ubuntu 18.04 + 20.04 as this is how I build for these on my website.

**Comment by EugenMayer** [comment]
Running on 20.04

**Comment by ianw1974** [comment]
Just running it now to check/verify, since this was working beginning of November when I built 10.0.5.

**Comment by ianw1974** [comment]
Built using podman without problems, and didn't even need to add this fix:

```
zcs-10.0.5_GA_0423.UBUNTU20_64.20231117085611.tgz
```

Are you sure you haven't edited my scripts or something that have caused this to fail, because it works perfectly fine with the current scripts in my repo and the Dockerfile.

Testing Docker so will update shortly if it's a docker thing.

**Comment by ianw1974** [comment]
Just built on my docker host as well:

```
zcs-10.0.5_GA_0423.UBUNTU20_64.20231117091323.tgz
```

I cannot replicate this problem, which means the script and Dockerfile I provide do work as intended.  If they have been changed/modified in anyway since downloading, then this could be the reason why yours isn't working.

I can add the fix, rather to my build script, so:

```
mkdir -p ~/.ivy2/cache
```

doing this way means it will create in the home directory of the user that is building Zimbra - be it root, or a normal user account.  Hard-coding to ```/root/.ivy2/cache``` would be wrong, since not everyone would build as root.  Obviously the Docker container does build as root which isn't so important since the container is destroyed afterwards and isn't going to affect a working system.  On a normal VPS or server that will remain running, then building as a normal user is preferred.

I would much prefer to find out what is causing the problem, rather than just introduce a workaround.  This shouldn't happen at all with either Ubuntu 18.04 or 20.04.  It does occur with Ubuntu 16.04 but then that is no longer supported so I didn't address that issue especially for that reason.

Even Ubuntu 18.04 has gone EOL now, although the script still supports it for the time being.  But that may change in the future.

If you can provide more info as to why this problem occurs for you - was something changed in the original Dockerfile, or what at your end is different that could cause this problem?  I for one, cannot replicate it anyway as I've just made two builds for 10.0.5 without any problems at all.

**Comment by EugenMayer** [comment]
I keep it vanilla

```yaml
name: docker

on:
  push:

env:
  IMAGE_FQDN: ghcr.io/kontextwork/zimbra-builder
  # actually that's the distro to build ON and FOR
  TARGET_DISTRO: ubuntu:20.04

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout us
        uses: actions/checkout@v4
        with:
          path: builder
      - name: Checkout zimbra-build-scripts
        uses: actions/checkout@v4
        with:
          repository: ianw1974/zimbra-build-scripts
          ref: main
          path: zimbra-build-scripts
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - name: Build builder
        uses: docker/build-push-action@v3
        with:
          context: zimbra-build-scripts
          platforms: linux/amd64
          push: true
          build-args: |
            # actually that's the distro to build ON and FOR
            RELEASE=${{ env.TARGET_DISTRO }}
          tags: |
            ${{ env.IMAGE_FQDN }}:latest
```

and then

```yaml
    - run: |
          set -e
          cd /home/git/zimbra-build-scripts/
          ./zimbra-build-helper.sh --build-zimbra
```

depening on #60 i for sure simply can share the entire project
